# These are supported funding model platforms

github: [wax911] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: wax911 # Replace with a single Patreon username
ko_fi: anitrend
issuehunt: anitrend
