language: android
jdk: oraclejdk8
dist: trusty
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - TRAVIS_SECURE_ENV_VARS=true

deploy:
  provider: firebase
  token:
    secure: BOvWypEnsGXVtIMtq1qBGIR58ywhMHexJQM147+XL1nmtWHf0YnVhAc/wcnOsJwmH+gdrmoFj8Rw33scOptjkuLCqdPTz1gyofQG0lineOVLw6iG4SIg5B1LJMPnxojKthraSTKWt19eviy5AQGkoGlWqk1ked5jiDJtJQo2Yj8kCcciIPv929lAKTwKl1z180upQKQN8VhEwnWVodqdDNc4lGlp9Kfz/iNSHF5j4m7NL04Yfn/KC4DJ6+28bNwwnWIB1IUySEY1NhnUi0ipBzm+rlET1qLo3qJZO1cWiSRX2phuH28Ls7vLtcvN1dJx9fcCd9i6877pL4ncplhnRSwbAlHEZxmLbHv8yNMM+Xw01cwXUcW5H10+4Q+93NuVWgxQqq1tVdInfXWKxPVg9jwRWU1RdS+lfzDFxjuj2TEtYxbOnBmQYK12jcjQlnt1gr4RycBkgXnODtSygUULiw4W65KIL6Fm/DvTIdMpNyopV/1VEcLLjQs+9uetXXjgITS1TIIYVNcVAsc1v/VYpiAQ0jnWE+gSaKyslPvHoC83zuN8ryF4VcsPpBTjI/KAqDM2MUaNuRUxIiHy8Q5oUpfV/03exQb3dxwtyM1TaLmrPaorQ6y5ecr3upOSFSRdX077kKJbsdbGO8VPJN5n/P4+2F96PbfKBK9KaDDqLCw=

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-x86-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-17

    # addons
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

licenses:
  - '.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - touch ./data/.config/secrets.properties
  - echo cliendId=\"cliend_id\" >> ./data/.config/secrets.properties
  - echo clientSecret=\"client_secret\" >> ./data/.config/secrets.properties
  
script:
    - ./gradlew test

before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "build-tools;28.0.3"
