schema: schema.graphql
documents: 'src/main/assets/graphql/*.graphql'
extensions:
  endpoints:
    AniList:
      url: https://graphql.anilist.co
      headers:
        user-agent: JS GraphQL
      introspect: true
    AniTrend:
      url: https://api.anitrend.co/graphql
      headers:
        User-Agent: "JS GraphQL"
        Accept: "*/*"
        HOST: "graphql.anitrend.co"
        Accept-Encoding: "gzip, deflate, br"
        Content-Type: "application/json"
      introspect: true
