schema: schema.graphql
extensions:
  endpoints:
    AniList:
      url: https://graphql.anilist.co
      headers:
        user-agent: JS GraphQL
      introspect: true
    AniTrend:
      #url: https://graphql.anitrend.co
      url: http://api.anitrend.docker.localhost/graphql
      headers:
        User-Agent: "JS GraphQL"
        Accept: "*/*"
        HOST: "graphql.anitrend.co"
        Accept-Encoding: "gzip, deflate, br"
        Accept-Language: "en-GB,en-US;q=0.9,en;q=0.8"
        Content-Type: "application/json"
      introspect: true
