query GetUserProfileOverview($id: Int) {
    User(id: $id) {
        id
        favourites {
            anime(page: 1, perPage: 6) {
                edges {
                    favouriteOrder
                    node {
                        ... UserProfileMediaPreview
                    }
                }
            }
            manga(page: 1, perPage: 6) {
                edges {
                    favouriteOrder
                    node {
                        ... UserProfileMediaPreview
                    }
                }
            }
        }
    }
    Page(page: 1, perPage: 6) {
        activities(userId: $id, sort: [ID_DESC], type: MEDIA_LIST) {
            ... UserProfileListActivity
        }
    }
}
