name: android-build-deploy

on:
  push:
    tags:
      - '*'

permissions:
  actions: write
  repository-projects: write

jobs:
  android-build-deploy:
    runs-on: ubuntu-22.04
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
      KOIN_PROPERTIES: ${{ secrets.KOIN_PROPERTIES }}
      KOIN_PROPERTIES_PASSPHRASE: ${{ secrets.KOIN_PROPERTIES_PASSPHRASE }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Increase swapfile
        run: |
          chmod +x .github/scripts/action-swap-increase.sh
          bash .github/scripts/action-swap-increase.sh
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          # cache: 'gradle'
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: android-build-deploy
          check-name: android-unit-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: set up pre-deploy configurations
        run: |
          chmod +x .github/scripts/pre-config.sh
          chmod +x .github/scripts/pre-deploy.sh
          bash .github/scripts/pre-config.sh
          bash .github/scripts/pre-deploy.sh
      - name: Post setup clean up
        run: |
          chmod +x .github/scripts/cleanup-temp-direcoty.sh
          bash .github/scripts/cleanup-temp-direcoty.sh
      - name: Fetch tags
        run: git fetch --tags --force
      - name: build release APKs
        run: ./gradlew assembleRelease --no-daemon
      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag_data
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "${{ steps.tag_data.outputs.git-tag-annotation }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            app/build/outputs/apk/**/release/*.apk
            app/build/outputs/apk/**/release/*.json
