name: Android

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure properties
      working-directory: ./data/.config
      run: |
      touch secrets.properties
      echo cliendId=\"cliend_id\" >> .secrets.properties
      echo clientSecret=\"client_secret\" >> .secrets.properties
    - name: Build with Gradle
      run: ./gradlew test
