name: Android dependency updates

on:
  schedule:
    - cron: '30 23 * * 5'

permissions:
  actions: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: set up staging configurations
      run: |
        chmod +x .github/scripts/pre-config.sh
        chmod +x .github/scripts/staging-config.sh
        ./.github/scripts/pre-config.sh
        ./.github/scripts/staging-config.sh
    - name: Gradle check for updates
      run: ./gradlew dependencyUpdates --stacktrace
    - name: Upload dependency updates report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-report
        path: build/dependencyUpdates/report.json
        retention-days: 7
