name: android-spotless

on:
  push:
    branches: [develop]
  pull_request:
    branches:
      - "*"

jobs:
  android-spotless:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Run spotless apply
        run: ./gradlew spotlessApply
      - name: Check for changes
        run: |
          git diff --exit-code || exit 0
        continue-on-error: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          signoff: true
          delete-branch: true
          commit-message: "automation: apply spotless linting"
          title: "platform: automated lint fix"
          body: |
            This PR was automatically generated to fix linting issues using spotless.
          branch: platform/auto-lint-fix
          labels: ":skateboard: skip-changelog"
          base: ${{ github.head_ref }}
