name: android-unit-test

on: [push]

jobs:
  android-unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Increase swapfile
      run: |
        chmod +x .github/scripts/action-swap-increase.sh
        bash .github/scripts/action-swap-increase.sh
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
        # cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Configure properties
      run: |
        chmod +x .github/scripts/staging-config.sh
        bash .github/scripts/staging-config.sh
    - name: Check Disk Space
      run: df -h
    - name: Gradle test
      run: ./gradlew test --stacktrace
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/**/TEST-*.xml'
