name: android-unit-test

on: [push, pull_request]

jobs:
  android-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Configure properties
      run: |
        chmod +x .github/scripts/staging-config.sh
        bash .github/scripts/staging-config.sh
    - name: Gradle test
      run: ./gradlew test --stacktrace
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/**/TEST-*.xml'
