name: Android firebase app distribution

on:
  push:
    branches:
      - 'release/*'

permissions:
  actions: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
      SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
      SECRETS_PROPERTIES_PASSPHRASE: ${{ secrets.SECRETS_PROPERTIES_PASSPHRASE }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: set up pre-deploy configurations
        run: |
          chmod +x .github/scripts/pre-config.sh
          chmod +x .github/scripts/pre-deploy.sh
          ./.github/scripts/pre-config.sh
          ./.github/scripts/pre-deploy.sh
      - name: build release
        run: |
          chmod +x gradlew
          ./gradlew test assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          # appId: ${{ secrets.FIREBASE_APP_ID }}
          # token: ${{ secrets.FIREBASE_TOKEN }}
          serviceCredentialsFile: app/google-services.json
          file: app/build/outputs/apk/release/app-release-google.apk
          groups: early-access-supporters
