name: Android unit test task

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure properties
      run: |
        chmod +x ./scripts/configuration.sh
        ./scripts/configuration.sh
    - name: Build with Gradle
      run: ./gradlew test --stacktrace
