name: Android build and deploy task

on:
  push:
    tags:
      - '*'

permissions:
  actions: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
      KOIN_PROPERTIES: ${{ secrets.KOIN_PROPERTIES }}
      KOIN_PROPERTIES_PASSPHRASE: ${{ secrets.KOIN_PROPERTIES_PASSPHRASE }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: set up pre-deploy configurations
        run: |
          chmod +x .github/scripts/pre-config.sh
          chmod +x .github/scripts/pre-deploy.sh
          ./.github/scripts/pre-config.sh
          ./.github/scripts/pre-deploy.sh
      - name: Fetch tags
        run: git fetch --tags --force
      - name: build release APKs
        run: ./gradlew test assembleRelease
      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag_data
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "${{ steps.tag_data.outputs.git-tag-annotation }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            app/build/outputs/apk/**/release/*.apk
            app/build/outputs/apk/**/release/*.json
