name: Android unit test task

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Configure properties
      run: |
        chmod +x .github/scripts/configuration.sh
        ./.github/scripts/configuration.sh
    - name: Gradle test
      run: ./gradlew test --stacktrace
