name: Release Drafter

on:
  push:
    branches: [master]

jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-config.yml
          commitish: master
          token: ${{ secrets.GITHUB_TOKEN }}
