name: version-update

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: version
        run: echo "${GITHUB_REF#refs/tags/}" > VERSION

      - name: Calculate version code
        id: code
        run: |
          IFS='.' read -ra VER <<< "$(cat VERSION)"
          MAJOR=$((VER[0] * 1000000000))
          MINOR=$((VER[1] * 1000000))
          PATCH=$((VER[2] * 1000))
          CODE=$((MAJOR + MINOR + PATCH))
          echo "version=$(cat VERSION)" > gradle/version.properties
          echo "code=$CODE" >> gradle/version.properties
          echo "name=v$(cat VERSION)" >> gradle/version.properties

      - name: Show version
        run: cat gradle/version.properties

      - name: Commit version.properties
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gradle/version.properties
          git commit -m "Bump version to $(cat VERSION)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          directory: .
